module.exports = {
  apps: [
    {
      name: 'seupercurso-api',
      cwd: './server',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
    },
    {
      name: 'seupercurso-client',
      cwd: './client',
      script: '.output/server/index.mjs',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
        NUXT_PUBLIC_API_BASE: 'https://api.seupercurso.esp.br',
        NUXT_PUBLIC_ORGANIZER_BASE: 'https://organizador.seupercurso.esp.br',
      },
    },
    {
      name: 'seupercurso-organizer',
      cwd: './organizer',
      script: '.output/server/index.mjs',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3002,
        NUXT_PUBLIC_API_BASE: 'https://api.seupercurso.esp.br',
        NUXT_PUBLIC_CLIENT_BASE: 'https://seupercurso.esp.br',
      },
    },
    {
      name: 'seupercurso-admin',
      cwd: './admin',
      script: '.output/server/index.mjs',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3003,
        NUXT_PUBLIC_API_BASE: 'https://api.seupercurso.esp.br',
      },
    },
  ],
};
